<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.OpenApi" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
		<PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Http" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
	</ItemGroup>

</Project>
