<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentAssertions"/>
		<PackageReference Include="Microsoft.NET.Test.Sdk"/>
		<PackageReference Include="NSubstitute"/>
		<PackageReference Include="NetArchTest.Rules"/>
		<PackageReference Include="xunit"/>
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\Shared.Test\Shared.Test.csproj" />
        <ProjectReference Include="..\Identity.Domain\Identity.Domain.csproj" />
        <ProjectReference Include="..\Identity.Application\Identity.Application.csproj" />
        <ProjectReference Include="..\Identity.Infrastructure\Identity.Infrastructure.csproj" />
        <ProjectReference Include="..\Identity.Presentation\Identity.Presentation.csproj" />
    </ItemGroup>

</Project>
